name: first-workflow

on:
    push:
        branches:
            - master

env:
    ENV: test

jobs:
    welcome_job:
        runs-on: ubuntu:latest
        env:
            name: welcome-job
        steps:
            - name: "Its a test welcome step"
              run: echo "this is a $ENV job of $name"

