name: Infra-auto-with-Terra

on: 
 push:
    branches:
     - main

 pull_request:
    branches:
     - main


jobs:
    Install_terraform:
        runs-on: self-hosted
        steps:
            - name: update the runner
              run: |
               echo "updating the ec2"
               sudo apt-get update -y

            - name: Install Terraform
              run: |
               echo "Installing Terraform..."
               sudo apt-get install -y gnupg software-properties-common curl
               curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
               sudo apt-add-repository "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
               sudo apt-get update && sudo apt-get install terraform

    Set-UP-Infra:
        runs-on: self-hosted
        needs: Install_terraform
        env:
            AWS_ACCESS_KEY_ID: ${{secrets.}}     
            AWS_SECRET_ACCESS_KEY_ID: ${{secrets.}}  
            
        steps:
            - name: Terraform init
              run: terraform init
              
            - name: Terraform validate
              run: terraform validate

            - name: Terraform plan
              run: terraform plan | grep "#"

            - name: Terraform apply
              run: terraform apply -auto-approve
